//
// Copyright © 2023 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

/// Representation of a Bank Account Funding Source
public struct BankAccountFundingSource: BaseFundingSource, Equatable {
    struct Constants {
        static let TypeName: String = "BankAccountFundingSource"
    }

    // MARK: - Conformance: FundingSource

    /// Identifier generated by the Virtual Cards Service.
    public let id: String

    /// Owner identifier of the funding source. Typically the user sub.
    public let owner: String

    /// Version assigned by the service.
    public let version: Int

    /// Virtual Cards service timestamp to when the funding source record was created.
    public let createdAt: Date

    /// Virtual Cards service timestamp to when the funding source record was last updated.
    public let updatedAt: Date

    /// Type of this funding source - always `BANK_ACCOUNT`
    public let type: FundingSourceType = .bankAccount

    /// Current state of the funding source.
    public let state: FundingSourceState

    /// Currency of the funding source.
    public let currency: String

    /// Unique fingerprint of a funding source.
    public let fingerprint: String

    // MARK: - BankAcountFundingSource

    /// Last 4 digits of the bank account of the funding source.
    public let last4: String

    /// Type of bank account represented by this funding source.
    public let bankAccountType: BankAccountType

    /// User authorization data used in completing or refreshing the funding source.
    public let authorization: SignedAuthorizationText

    /// Construct a bank account funding source.
    /// 
    /// - Parameters:
    ///   - id: Identifier generated by the Virtual Cards Service.
    ///   - owner: Owner identifier of the funding source. Typically the user sub.
    ///   - version: Version assigned by the service.
    ///   - createdAt: Virtual Cards service timestamp to when the funding source record was created.
    ///   - updatedAt: Virtual Cards service timestamp to when the funding source record was last updated.
    ///   - state: Current state of the funding source.
    ///   - currency: Currency of the funding source.
    ///   - fingerprint: Unique fingerprint of a funding source.   
    ///   - last4: Last 4 digits of the bank account of the funding source.
    ///   - bankAccountType: Type of bank account represented by this funding source.
    ///   - authorization: User authorization data used in completing or refreshing the funding source.
    public init(
        id: String,
        owner: String,
        version: Int,
        createdAt: Date,
        updatedAt: Date,
        state: FundingSourceState,
        currency: String,
        fingerprint: String,
        last4: String,
        bankAccountType: BankAccountType,
        authorization: SignedAuthorizationText
    ) {
        self.id = id
        self.owner = owner
        self.version = version
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.state = state
        self.currency = currency
        self.fingerprint = fingerprint
        self.last4 = last4
        self.bankAccountType = bankAccountType
        self.authorization = authorization
    }
}
