//
// Copyright © 2023 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

/// Representation of a Credit Card Funding Source
public struct CreditCardFundingSource: BaseFundingSource, Equatable {
    struct Constants {
        static let TypeName: String = "CreditCardFundingSource"
    }

    // MARK: - Conformance: FundingSource

    /// Identifier generated by the Virtual Cards Service.
    public let id: String

    /// Owner identifier of the funding source. Typically the user sub.
    public let owner: String

    /// Version assigned by the service.
    public let version: Int

    /// Virtual Cards service timestamp to when the funding source record was created.
    public let createdAt: Date

    /// Virtual Cards service timestamp to when the funding source record was last updated.
    public let updatedAt: Date

    /// Type of this funding source - always `CREDIT_CARD`.
    public let type: FundingSourceType = .creditCard

    /// Current state of the funding source.
    public let state: FundingSourceState

    /// Currency of the funding source.
    public let currency: String

    /// Unique fingerprint of a funding source.
    public let fingerprint: String

    // MARK: - CreditCardFundingSource

    /// Last 4 digits of the card of the funding source.
    public let last4: String

    /// Payment Method network of the funding source.
    public let network: CreditCardNetwork

    /// Type of card represented by this funding source.
    public let cardType: CardType

    /// Construct a credit card funding source.
    /// 
    /// - Parameters:
    ///   - id: Identifier generated by the Virtual Cards Service.
    ///   - owner: Owner identifier of the funding source. Typically the user sub.
    ///   - version: Version assigned by the service.
    ///   - createdAt: Virtual Cards service timestamp to when the funding source record was created.
    ///   - updatedAt: Virtual Cards service timestamp to when the funding source record was last updated.
    ///   - state: Current state of the funding source.
    ///   - currency: Currency of the funding source.
    ///   - fingerprint: Unique fingerprint of a funding source.
    ///   - last4: Last 4 digits of the card number of the funding source.
    ///   - network: Payment Method network of the funding source.
    ///   - cardType: Type of card represented by this funding source.
    public init(
        id: String,
        owner: String,
        version: Int,
        createdAt: Date,
        updatedAt: Date,
        state: FundingSourceState,
        currency: String,
        fingerprint: String,
        last4: String,
        network: CreditCardNetwork,
        cardType: CardType
    ) {
        self.id = id
        self.owner = owner
        self.version = version
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.state = state
        self.currency = currency
        self.fingerprint = fingerprint
        self.last4 = last4
        self.network = network
        self.cardType = cardType
    }
}
